// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../ffi.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 初始化 Legado 运行时（首次调用时创建 tokio runtime）
Future<void> init() => RustLib.instance.api.crateFfiFfiInit();

/// 获取版本号
Future<String> version() => RustLib.instance.api.crateFfiFfiVersion();

/// 打开数据库并初始化全局连接
Future<void> dbOpen({required String path}) =>
    RustLib.instance.api.crateFfiFfiDbOpen(path: path);

/// 获取书架上所有书籍（JSON 数组）
Future<String> bookshelfList() =>
    RustLib.instance.api.crateFfiFfiBookshelfList();

/// 添加书籍到书架（传入 JSON 字符串），返回书籍信息（JSON）
Future<String> bookshelfAdd({required String bookJson}) =>
    RustLib.instance.api.crateFfiFfiBookshelfAdd(bookJson: bookJson);

/// 更新书籍信息（传入 JSON 字符串）
Future<void> bookshelfUpdate({required String bookJson}) =>
    RustLib.instance.api.crateFfiFfiBookshelfUpdate(bookJson: bookJson);

/// 按 bookUrl 删除书籍
Future<void> bookshelfDelete({required String bookUrl}) =>
    RustLib.instance.api.crateFfiFfiBookshelfDelete(bookUrl: bookUrl);

/// 按 bookUrl 获取书籍详情（JSON，可能为 null）
Future<String> bookshelfGet({required String bookUrl}) =>
    RustLib.instance.api.crateFfiFfiBookshelfGet(bookUrl: bookUrl);

/// 更新阅读进度
Future<void> readerUpdateProgress({
  required String bookUrl,
  required int chapterIndex,
  required int chapterPos,
}) => RustLib.instance.api.crateFfiFfiReaderUpdateProgress(
  bookUrl: bookUrl,
  chapterIndex: chapterIndex,
  chapterPos: chapterPos,
);

/// 获取所有书源列表（JSON 数组）
Future<String> sourceList() => RustLib.instance.api.crateFfiFfiSourceList();

/// 获取所有启用的书源（JSON 数组）
Future<String> sourceListEnabled() =>
    RustLib.instance.api.crateFfiFfiSourceListEnabled();

/// 添加书源（传入 JSON 字符串），返回书源信息（JSON）
Future<String> sourceAdd({required String sourceJson}) =>
    RustLib.instance.api.crateFfiFfiSourceAdd(sourceJson: sourceJson);

/// 更新书源（传入 JSON 字符串）
Future<void> sourceUpdate({required String sourceJson}) =>
    RustLib.instance.api.crateFfiFfiSourceUpdate(sourceJson: sourceJson);

/// 按 URL 删除书源
Future<void> sourceDelete({required String sourceUrl}) =>
    RustLib.instance.api.crateFfiFfiSourceDelete(sourceUrl: sourceUrl);

/// 启用书源
Future<void> sourceEnable({required String sourceUrl}) =>
    RustLib.instance.api.crateFfiFfiSourceEnable(sourceUrl: sourceUrl);

/// 禁用书源
Future<void> sourceDisable({required String sourceUrl}) =>
    RustLib.instance.api.crateFfiFfiSourceDisable(sourceUrl: sourceUrl);

/// 批量导入书源（JSON 数组），返回成功导入的数量
Future<int> sourceImport({required String jsonArray}) =>
    RustLib.instance.api.crateFfiFfiSourceImport(jsonArray: jsonArray);

/// 导出所有书源为 JSON 数组
Future<String> sourceExport() => RustLib.instance.api.crateFfiFfiSourceExport();

/// 搜索书籍（返回 JSON 数组）
///
/// `keyword` — 搜索关键词
/// `source_urls_json` — 可选 JSON 数组，指定搜索的书源 URL 列表；为空则搜索所有启用的书源
Future<String> searchBooks({
  required String keyword,
  required String sourceUrlsJson,
}) => RustLib.instance.api.crateFfiFfiSearchBooks(
  keyword: keyword,
  sourceUrlsJson: sourceUrlsJson,
);

/// 多源并行搜索（返回 JSON 数组）
///
/// `query` — 搜索关键词
/// `source_urls_json` — 可选 JSON 数组，指定搜索的书源 URL 列表；为空则搜索所有启用的书源
Future<String> searchMulti({
  required String query,
  required String sourceUrlsJson,
}) => RustLib.instance.api.crateFfiFfiSearchMulti(
  query: query,
  sourceUrlsJson: sourceUrlsJson,
);

/// 取消正在进行的搜索
Future<void> searchCancel() => RustLib.instance.api.crateFfiFfiSearchCancel();

/// 获取书籍的章节列表（JSON）
Future<String> readerGetChapters({required String bookUrl}) =>
    RustLib.instance.api.crateFfiFfiReaderGetChapters(bookUrl: bookUrl);

/// 获取章节正文内容
///
/// 本地书籍直接返回正文文本；在线书籍返回 JSON（含 chapter_url 等信息，需 Dart 侧进一步获取）
Future<String> readerGetContent({
  required String bookUrl,
  required int chapterIndex,
}) => RustLib.instance.api.crateFfiFfiReaderGetContent(
  bookUrl: bookUrl,
  chapterIndex: chapterIndex,
);

/// 获取章节正文内容（不应用替换规则，用于内容搜索）
///
/// 取正文流程与 [`reader_get_content`] 相同，但净化时关闭替换规则，
/// 与 Android 书内搜索默认行为（replaceEnabled=false）对齐。
Future<String> readerGetContentRaw({
  required String bookUrl,
  required int chapterIndex,
}) => RustLib.instance.api.crateFfiFfiReaderGetContentRaw(
  bookUrl: bookUrl,
  chapterIndex: chapterIndex,
);

/// 从网络刷新书籍目录（返回 JSON 章节列表）
///
/// `book_url` — 书籍详情页 URL
/// `source_url` — 书源 URL
Future<String> readerRefreshToc({
  required String bookUrl,
  required String sourceUrl,
}) => RustLib.instance.api.crateFfiFfiReaderRefreshToc(
  bookUrl: bookUrl,
  sourceUrl: sourceUrl,
);

/// 获取章节正文内容（在线抓取，带 DB 缓存，返回真实正文文本）
///
/// `book_url` — 书籍 URL
/// `chapter_url` — 章节 URL
/// `source_url` — 书源 URL
Future<String> readerFetchContent({
  required String bookUrl,
  required String chapterUrl,
  required String sourceUrl,
}) => RustLib.instance.api.crateFfiFfiReaderFetchContent(
  bookUrl: bookUrl,
  chapterUrl: chapterUrl,
  sourceUrl: sourceUrl,
);

/// 检测书籍文件格式（JSON）
Future<String> importDetectFormat({required String filePath}) =>
    RustLib.instance.api.crateFfiFfiImportDetectFormat(filePath: filePath);

/// 解析书籍元数据（返回 JSON 字符串）
Future<String> importParseMetadata({required String filePath}) =>
    RustLib.instance.api.crateFfiFfiImportParseMetadata(filePath: filePath);

/// 导入本地书籍到书架（JSON）
Future<String> importLocalBook({required String filePath}) =>
    RustLib.instance.api.crateFfiFfiImportLocalBook(filePath: filePath);

/// 获取所有 RSS 源列表（JSON 数组）
Future<String> rssListSources() =>
    RustLib.instance.api.crateFfiFfiRssListSources();

/// 添加 RSS 源（传入 JSON 字符串），返回源信息（JSON）
Future<String> rssAddSource({required String sourceJson}) =>
    RustLib.instance.api.crateFfiFfiRssAddSource(sourceJson: sourceJson);

/// 删除 RSS 源
Future<void> rssDeleteSource({required String sourceUrl}) =>
    RustLib.instance.api.crateFfiFfiRssDeleteSource(sourceUrl: sourceUrl);

/// 获取 RSS 源的文章列表（JSON 数组）
Future<String> rssFetchArticles({required String sourceUrl}) =>
    RustLib.instance.api.crateFfiFfiRssFetchArticles(sourceUrl: sourceUrl);

/// 获取所有 RSS 收藏（JSON 数组）
Future<String> rssStarList() => RustLib.instance.api.crateFfiFfiRssStarList();

/// 添加 RSS 收藏，返回收藏时间戳
Future<PlatformInt64> rssStarAdd({
  required String sourceUrl,
  required String title,
  required String link,
}) => RustLib.instance.api.crateFfiFfiRssStarAdd(
  sourceUrl: sourceUrl,
  title: title,
  link: link,
);

/// 取消 RSS 收藏（按 link 删除）
Future<bool> rssStarDelete({required String link}) =>
    RustLib.instance.api.crateFfiFfiRssStarDelete(link: link);

/// 判断是否已收藏
Future<bool> rssStarIsStarred({required String link}) =>
    RustLib.instance.api.crateFfiFfiRssStarIsStarred(link: link);

/// 获取最近搜索历史（JSON 数组）
Future<String> searchHistoryList({required int limit}) =>
    RustLib.instance.api.crateFfiFfiSearchHistoryList(limit: limit);

/// 添加搜索关键词，返回时间戳
Future<PlatformInt64> searchHistoryAdd({
  required String keyword,
  required String bookName,
}) => RustLib.instance.api.crateFfiFfiSearchHistoryAdd(
  keyword: keyword,
  bookName: bookName,
);

/// 删除搜索关键词
Future<bool> searchHistoryDelete({required String keyword}) =>
    RustLib.instance.api.crateFfiFfiSearchHistoryDelete(keyword: keyword);

/// 清空搜索历史
Future<bool> searchHistoryClear() =>
    RustLib.instance.api.crateFfiFfiSearchHistoryClear();

/// 搜索可替换的书源（返回 JSON 格式的匹配结果列表）
///
/// `book_name` — 当前书籍名称
/// `author` — 当前作者
Future<String> sourceSwitchSearch({
  required String bookName,
  required String author,
}) => RustLib.instance.api.crateFfiFfiSourceSwitchSearch(
  bookName: bookName,
  author: author,
);

/// 切换到新书源（返回更新后的书籍 JSON）
///
/// `book_url` — 当前书籍的 bookUrl
/// `new_source_url` — 新书源的 URL
/// `new_book_url` — 新书源中该书籍的详情页 URL
Future<String> sourceSwitchApply({
  required String bookUrl,
  required String newSourceUrl,
  required String newBookUrl,
}) => RustLib.instance.api.crateFfiFfiSourceSwitchApply(
  bookUrl: bookUrl,
  newSourceUrl: newSourceUrl,
  newBookUrl: newBookUrl,
);

/// HTTP GET 请求，返回 JSON 格式的响应
Future<String> httpGet({required String url}) =>
    RustLib.instance.api.crateFfiFfiHttpGet(url: url);

/// HTTP POST 请求，返回 JSON 格式的响应
Future<String> httpPost({required String url, required String body}) =>
    RustLib.instance.api.crateFfiFfiHttpPost(url: url, body: body);

/// 搜索书籍（书源规则驱动，返回 JSON 数组）
///
/// `source_json` — BookSource JSON 字符串
/// `query` — 搜索关键词
/// `page` — 页码（从 1 开始）
Future<String> webbookSearch({
  required String sourceJson,
  required String query,
  required int page,
}) => RustLib.instance.api.crateFfiFfiWebbookSearch(
  sourceJson: sourceJson,
  query: query,
  page: page,
);

/// 获取书籍详情（返回 WebBookInfo JSON）
///
/// `source_json` — BookSource JSON 字符串
/// `book_url` — 书籍详情页 URL
Future<String> webbookInfo({
  required String sourceJson,
  required String bookUrl,
}) => RustLib.instance.api.crateFfiFfiWebbookInfo(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);

/// 获取章节列表（返回 JSON 数组）
///
/// `source_json` — BookSource JSON 字符串
/// `book_url` — 书籍详情页 URL
Future<String> webbookChapters({
  required String sourceJson,
  required String bookUrl,
}) => RustLib.instance.api.crateFfiFfiWebbookChapters(
  sourceJson: sourceJson,
  bookUrl: bookUrl,
);

/// 获取章节正文内容
///
/// `source_json` — BookSource JSON 字符串
/// `chapter_json` — WebChapter JSON 字符串
Future<String> webbookContent({
  required String sourceJson,
  required String chapterJson,
}) => RustLib.instance.api.crateFfiFfiWebbookContent(
  sourceJson: sourceJson,
  chapterJson: chapterJson,
);

/// 解析 exploreUrl 为分类列表（返回 JSON 数组）
///
/// `explore_url` — 书源的 exploreUrl 字段
Future<String> exploreParseUrl({required String exploreUrl}) =>
    RustLib.instance.api.crateFfiFfiExploreParseUrl(exploreUrl: exploreUrl);

/// 抓取发现分类的书籍列表（返回 WebSearchResult JSON 数组）
///
/// `source_json` — BookSource JSON 字符串
/// `url` — 分类 URL
/// `page` — 页码（从 1 开始）
Future<String> exploreFetchBooks({
  required String sourceJson,
  required String url,
  required int page,
}) => RustLib.instance.api.crateFfiFfiExploreFetchBooks(
  sourceJson: sourceJson,
  url: url,
  page: page,
);

/// 使用规则解析内容，返回 JSON 格式的结果
Future<String> parseRule({
  required String content,
  required String rule,
  required String ruleType,
}) => RustLib.instance.api.crateFfiFfiParseRule(
  content: content,
  rule: rule,
  ruleType: ruleType,
);

/// 执行 JS 脚本（未启用 quickjs 时返回错误）
Future<String> jsEval({required String script}) =>
    RustLib.instance.api.crateFfiFfiJsEval(script: script);

/// 获取书籍的所有书签（JSON 数组）
Future<String> bookmarkGetAll({required String bookName}) =>
    RustLib.instance.api.crateFfiFfiBookmarkGetAll(bookName: bookName);

/// 添加书签，返回书签 id
Future<PlatformInt64> bookmarkAdd({
  required String bookName,
  required String bookAuthor,
  required int chapterIndex,
  required int chapterPos,
  required String chapterName,
  required String bookText,
  required String content,
}) => RustLib.instance.api.crateFfiFfiBookmarkAdd(
  bookName: bookName,
  bookAuthor: bookAuthor,
  chapterIndex: chapterIndex,
  chapterPos: chapterPos,
  chapterName: chapterName,
  bookText: bookText,
  content: content,
);

/// 删除书签
Future<void> bookmarkDelete({required PlatformInt64 bookmarkId}) =>
    RustLib.instance.api.crateFfiFfiBookmarkDelete(bookmarkId: bookmarkId);

/// 搜索书签（JSON 数组）
Future<String> bookmarkSearch({required String keyword}) =>
    RustLib.instance.api.crateFfiFfiBookmarkSearch(keyword: keyword);

/// 获取所有书签（JSON 数组）
Future<String> bookmarkList() => RustLib.instance.api.crateFfiFfiBookmarkList();

/// 获取所有替换规则（JSON 数组）
Future<String> replaceRuleList() =>
    RustLib.instance.api.crateFfiFfiReplaceRuleList();

/// 添加替换规则，返回规则 id
Future<PlatformInt64> replaceRuleAdd({
  required String name,
  required String pattern,
  required String replacement,
  required bool isRegex,
  required String scope,
}) => RustLib.instance.api.crateFfiFfiReplaceRuleAdd(
  name: name,
  pattern: pattern,
  replacement: replacement,
  isRegex: isRegex,
  scope: scope,
);

/// 更新替换规则
Future<void> replaceRuleUpdate({
  required PlatformInt64 ruleId,
  required String name,
  required String pattern,
  required String replacement,
  required bool isRegex,
  required bool isEnabled,
}) => RustLib.instance.api.crateFfiFfiReplaceRuleUpdate(
  ruleId: ruleId,
  name: name,
  pattern: pattern,
  replacement: replacement,
  isRegex: isRegex,
  isEnabled: isEnabled,
);

/// 删除替换规则
Future<void> replaceRuleDelete({required PlatformInt64 ruleId}) =>
    RustLib.instance.api.crateFfiFfiReplaceRuleDelete(ruleId: ruleId);

/// 获取启用的替换规则（JSON 数组，用于阅读时应用）
Future<String> replaceRuleEnabled() =>
    RustLib.instance.api.crateFfiFfiReplaceRuleEnabled();

/// 启用/禁用替换规则
Future<void> replaceRuleSetEnabled({
  required PlatformInt64 ruleId,
  required bool enabled,
}) => RustLib.instance.api.crateFfiFfiReplaceRuleSetEnabled(
  ruleId: ruleId,
  enabled: enabled,
);

/// 获取所有阅读记录（JSON 数组）
Future<String> readRecordList() =>
    RustLib.instance.api.crateFfiFfiReadRecordList();

/// 添加/更新阅读记录，返回阅读时长
Future<PlatformInt64> readRecordUpsert({
  required String bookName,
  required PlatformInt64 readTime,
}) => RustLib.instance.api.crateFfiFfiReadRecordUpsert(
  bookName: bookName,
  readTime: readTime,
);

/// 删除阅读记录
Future<bool> readRecordDelete({required String bookName}) =>
    RustLib.instance.api.crateFfiFfiReadRecordDelete(bookName: bookName);

/// 清空所有阅读记录
Future<bool> readRecordClear() =>
    RustLib.instance.api.crateFfiFfiReadRecordClear();

/// 获取所有书籍分组（JSON 数组）
Future<String> bookGroupList() =>
    RustLib.instance.api.crateFfiFfiBookGroupList();

/// 添加书籍分组，返回新分组 ID
Future<PlatformInt64> bookGroupAdd({
  required String groupName,
  required String cover,
  required int order,
}) => RustLib.instance.api.crateFfiFfiBookGroupAdd(
  groupName: groupName,
  cover: cover,
  order: order,
);

/// 更新书籍分组
Future<bool> bookGroupUpdate({
  required PlatformInt64 id,
  required String groupName,
  required String cover,
  required int order,
}) => RustLib.instance.api.crateFfiFfiBookGroupUpdate(
  id: id,
  groupName: groupName,
  cover: cover,
  order: order,
);

/// 删除书籍分组
Future<bool> bookGroupDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateFfiFfiBookGroupDelete(id: id);

/// 设置分组显示状态
Future<bool> bookGroupSetShow({
  required PlatformInt64 id,
  required bool show_,
}) => RustLib.instance.api.crateFfiFfiBookGroupSetShow(id: id, show_: show_);

/// 获取今日阅读统计（JSON）
Future<String> statsToday() => RustLib.instance.api.crateFfiFfiStatsToday();

/// 获取最近 N 天每日统计（JSON 数组）
Future<String> statsDaily({required int days}) =>
    RustLib.instance.api.crateFfiFfiStatsDaily(days: days);

/// 获取按书籍分组的统计（JSON 数组）
Future<String> statsByBook() => RustLib.instance.api.crateFfiFfiStatsByBook();

/// 获取阅读热力图数据（JSON 数组）
Future<String> statsHeatmap({required int days}) =>
    RustLib.instance.api.crateFfiFfiStatsHeatmap(days: days);

/// 获取缓存总大小（字节）
Future<PlatformInt64> cacheGetSize() =>
    RustLib.instance.api.crateFfiFfiCacheGetSize();

/// 清空所有缓存
Future<bool> cacheClear() => RustLib.instance.api.crateFfiFfiCacheClear();

/// 获取章节缓存内容
Future<String> cacheGetChapter({
  required String bookUrl,
  required int chapterIndex,
}) => RustLib.instance.api.crateFfiFfiCacheGetChapter(
  bookUrl: bookUrl,
  chapterIndex: chapterIndex,
);

/// 获取缓存书籍数量
Future<int> cacheGetBookCount() =>
    RustLib.instance.api.crateFfiFfiCacheGetBookCount();

/// 获取缓存章节数量
Future<int> cacheGetChapterCount() =>
    RustLib.instance.api.crateFfiFfiCacheGetChapterCount();

/// 清除指定时间之前的缓存
Future<bool> cacheClearBefore({required PlatformInt64 beforeTimestampMs}) =>
    RustLib.instance.api.crateFfiFfiCacheClearBefore(
      beforeTimestampMs: beforeTimestampMs,
    );

/// 获取配置项
Future<String> configGet({required String key}) =>
    RustLib.instance.api.crateFfiFfiConfigGet(key: key);

/// 设置配置项
Future<bool> configSet({required String key, required String value}) =>
    RustLib.instance.api.crateFfiFfiConfigSet(key: key, value: value);

/// 获取所有配置（JSON 对象）
Future<String> configGetAll() => RustLib.instance.api.crateFfiFfiConfigGetAll();

/// 获取所有 HTTP TTS 源（JSON 数组）
Future<String> httpTtsList() => RustLib.instance.api.crateFfiFfiHttpTtsList();

/// 添加 HTTP TTS 源，返回新 ID
Future<PlatformInt64> httpTtsAdd({required String name, required String url}) =>
    RustLib.instance.api.crateFfiFfiHttpTtsAdd(name: name, url: url);

/// 更新 HTTP TTS 源
Future<bool> httpTtsUpdate({
  required PlatformInt64 id,
  required String name,
  required String url,
}) =>
    RustLib.instance.api.crateFfiFfiHttpTtsUpdate(id: id, name: name, url: url);

/// 删除 HTTP TTS 源
Future<bool> httpTtsDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateFfiFfiHttpTtsDelete(id: id);

/// 设置 HTTP TTS 源启用/禁用
Future<bool> httpTtsSetEnabled({
  required PlatformInt64 id,
  required bool enabled,
}) =>
    RustLib.instance.api.crateFfiFfiHttpTtsSetEnabled(id: id, enabled: enabled);

/// 获取音频播放进度（毫秒）
Future<PlatformInt64> audioGetProgress({
  required String bookUrl,
  required int chapterIndex,
}) => RustLib.instance.api.crateFfiFfiAudioGetProgress(
  bookUrl: bookUrl,
  chapterIndex: chapterIndex,
);

/// 保存音频播放进度
Future<bool> audioSaveProgress({
  required String bookUrl,
  required int chapterIndex,
  required PlatformInt64 position,
}) => RustLib.instance.api.crateFfiFfiAudioSaveProgress(
  bookUrl: bookUrl,
  chapterIndex: chapterIndex,
  position: position,
);

/// 创建备份到指定路径，返回备份文件路径
Future<String> backupCreate({required String path}) =>
    RustLib.instance.api.crateFfiFfiBackupCreate(path: path);

/// 从备份文件恢复，返回恢复统计（JSON）
Future<String> backupRestore({required String path}) =>
    RustLib.instance.api.crateFfiFfiBackupRestore(path: path);

/// 列出备份文件（JSON 数组）
Future<String> backupList({required String dir}) =>
    RustLib.instance.api.crateFfiFfiBackupList(dir: dir);

/// 启动 legado-server，返回状态消息
Future<String> serverStart({required int port}) =>
    RustLib.instance.api.crateFfiFfiServerStart(port: port);

/// 停止服务器
Future<String> serverStop() => RustLib.instance.api.crateFfiFfiServerStop();

/// 获取服务器状态（JSON）
Future<String> serverStatus() => RustLib.instance.api.crateFfiFfiServerStatus();

/// 获取所有用户（JSON 数组）
Future<String> userGetAll() => RustLib.instance.api.crateFfiFfiUserGetAll();

/// 保存用户，返回用户 ID
Future<PlatformInt64> userSave({
  required String username,
  required String password,
  required String sourceUrl,
}) => RustLib.instance.api.crateFfiFfiUserSave(
  username: username,
  password: password,
  sourceUrl: sourceUrl,
);

/// 删除用户
Future<bool> userDelete({required String username}) =>
    RustLib.instance.api.crateFfiFfiUserDelete(username: username);

/// 用户登录
Future<bool> userLogin({required String username, required String password}) =>
    RustLib.instance.api.crateFfiFfiUserLogin(
      username: username,
      password: password,
    );

/// 用户登出
Future<bool> userLogout({required String username}) =>
    RustLib.instance.api.crateFfiFfiUserLogout(username: username);

/// 检查登录状态
Future<bool> userCheckLogin({required String username}) =>
    RustLib.instance.api.crateFfiFfiUserCheckLogin(username: username);

/// 列出 WebDAV 远程目录（JSON 数组）
Future<String> webdavListDir({
  required String configJson,
  required String path,
}) => RustLib.instance.api.crateFfiFfiWebdavListDir(
  configJson: configJson,
  path: path,
);

/// 上传文件到 WebDAV
Future<void> webdavUpload({
  required String configJson,
  required String path,
  required String data,
}) => RustLib.instance.api.crateFfiFfiWebdavUpload(
  configJson: configJson,
  path: path,
  data: data,
);

/// 从 WebDAV 下载文件
Future<String> webdavDownload({
  required String configJson,
  required String path,
}) => RustLib.instance.api.crateFfiFfiWebdavDownload(
  configJson: configJson,
  path: path,
);

/// 删除 WebDAV 远程文件
Future<void> webdavDelete({required String configJson, required String path}) =>
    RustLib.instance.api.crateFfiFfiWebdavDelete(
      configJson: configJson,
      path: path,
    );

/// WebDAV 全量同步（返回 JSON: {"books": "...", "sources": "..."}）
Future<String> webdavFullSync({
  required String configJson,
  required String localBooks,
  required String localSources,
}) => RustLib.instance.api.crateFfiFfiWebdavFullSync(
  configJson: configJson,
  localBooks: localBooks,
  localSources: localSources,
);

/// 添加下载任务，返回任务 ID
Future<String> downloadAddTask({
  required String bookUrl,
  required String chapterUrl,
  required String chapterTitle,
  required int chapterIndex,
  required int priority,
}) => RustLib.instance.api.crateFfiFfiDownloadAddTask(
  bookUrl: bookUrl,
  chapterUrl: chapterUrl,
  chapterTitle: chapterTitle,
  chapterIndex: chapterIndex,
  priority: priority,
);

/// 获取下载统计信息（JSON）
Future<String> downloadGetStats() =>
    RustLib.instance.api.crateFfiFfiDownloadGetStats();

/// 获取指定书籍的下载任务（JSON 数组）
Future<String> downloadListByBook({required String bookUrl}) =>
    RustLib.instance.api.crateFfiFfiDownloadListByBook(bookUrl: bookUrl);

/// 暂停所有下载
Future<void> downloadPauseAll() =>
    RustLib.instance.api.crateFfiFfiDownloadPauseAll();

/// 恢复所有下载
Future<void> downloadResumeAll() =>
    RustLib.instance.api.crateFfiFfiDownloadResumeAll();

/// 移除下载任务
Future<void> downloadRemoveTask({required String taskId}) =>
    RustLib.instance.api.crateFfiFfiDownloadRemoveTask(taskId: taskId);

/// 更新下载进度
Future<void> downloadUpdateProgress({
  required String taskId,
  required double progress,
}) => RustLib.instance.api.crateFfiFfiDownloadUpdateProgress(
  taskId: taskId,
  progress: progress,
);

/// 获取指定章节的所有评论（JSON 数组）
Future<String> reviewGetByChapter({
  required String bookUrl,
  required int chapterIndex,
}) => RustLib.instance.api.crateFfiFfiReviewGetByChapter(
  bookUrl: bookUrl,
  chapterIndex: chapterIndex,
);

/// 添加评论，返回评论 ID
Future<PlatformInt64> reviewAdd({
  required String bookUrl,
  required int chapterIndex,
  required int paragraphIndex,
  required String content,
  required String author,
}) => RustLib.instance.api.crateFfiFfiReviewAdd(
  bookUrl: bookUrl,
  chapterIndex: chapterIndex,
  paragraphIndex: paragraphIndex,
  content: content,
  author: author,
);

/// 删除评论
Future<bool> reviewDelete({required PlatformInt64 id}) =>
    RustLib.instance.api.crateFfiFfiReviewDelete(id: id);

/// 点赞评论
Future<void> reviewLike({required PlatformInt64 id}) =>
    RustLib.instance.api.crateFfiFfiReviewLike(id: id);

/// 导出书籍（返回 ExportResult JSON）
///
/// # 参数
/// - `book_url`: 书籍 URL
/// - `format`: 导出格式（txt/epub/html）
/// - `include_toc`: 是否包含目录
Future<String> bookExport({
  required String bookUrl,
  required String format,
  required bool includeToc,
}) => RustLib.instance.api.crateFfiFfiBookExport(
  bookUrl: bookUrl,
  format: format,
  includeToc: includeToc,
);

/// 获取导出预览信息（返回 ExportResult JSON）
Future<String> bookExportInfo({
  required String bookUrl,
  required String format,
}) => RustLib.instance.api.crateFfiFfiBookExportInfo(
  bookUrl: bookUrl,
  format: format,
);

/// 导入 ZIP 压缩包中的书籍文件（返回 ArchiveImportResult JSON）
Future<String> archiveImportZip({
  required String zipPath,
  required String outputDir,
}) => RustLib.instance.api.crateFfiFfiArchiveImportZip(
  zipPath: zipPath,
  outputDir: outputDir,
);

/// 导入 RAR 压缩包中的书籍文件（支持加密，返回 ArchiveImportResult JSON）
Future<String> archiveImportRar({
  required String rarPath,
  required String outputDir,
  String? password,
}) => RustLib.instance.api.crateFfiFfiArchiveImportRar(
  rarPath: rarPath,
  outputDir: outputDir,
  password: password,
);

/// 列出 ZIP 压缩包中的书籍文件名（不解压，返回 JSON 数组）
Future<String> archiveListZipFiles({required String zipPath}) =>
    RustLib.instance.api.crateFfiFfiArchiveListZipFiles(zipPath: zipPath);

/// 列出 RAR 压缩包中的书籍文件名（不解压，返回 JSON 数组）
Future<String> archiveListRarFiles({
  required String rarPath,
  String? password,
}) => RustLib.instance.api.crateFfiFfiArchiveListRarFiles(
  rarPath: rarPath,
  password: password,
);

/// 检测 TXT 文件编码（返回 EncodingResult JSON）
Future<String> archiveDetectEncoding({required String filePath}) =>
    RustLib.instance.api.crateFfiFfiArchiveDetectEncoding(filePath: filePath);

/// 转换 TXT 文件编码（返回 ConvertResult JSON）
Future<String> archiveConvertEncoding({
  required String filePath,
  required String fromEncoding,
  required String toEncoding,
}) => RustLib.instance.api.crateFfiFfiArchiveConvertEncoding(
  filePath: filePath,
  fromEncoding: fromEncoding,
  toEncoding: toEncoding,
);

/// 判断文件是否为压缩包格式
Future<bool> archiveIsArchive({required String filePath}) =>
    RustLib.instance.api.crateFfiFfiArchiveIsArchive(filePath: filePath);

/// 创建 QUIC 客户端（config_json 为空时使用默认配置）
Future<String> quicCreateClient({String? configJson}) =>
    RustLib.instance.api.crateFfiFfiQuicCreateClient(configJson: configJson);

/// 通过 QUIC 发送 GET 请求（返回响应 JSON）
Future<String> quicGet({required String url, String? headersJson}) =>
    RustLib.instance.api.crateFfiFfiQuicGet(url: url, headersJson: headersJson);

/// 通过 QUIC 发送 POST 请求（body 为 base64 编码，返回响应 JSON）
Future<String> quicPost({
  required String url,
  required String bodyBase64,
  String? headersJson,
}) => RustLib.instance.api.crateFfiFfiQuicPost(
  url: url,
  bodyBase64: bodyBase64,
  headersJson: headersJson,
);

/// QUIC 性能测试（返回 PerformanceMetrics JSON）
Future<String> quicPerformanceTest({required String url}) =>
    RustLib.instance.api.crateFfiFfiQuicPerformanceTest(url: url);

/// 检查 QUIC 客户端是否已初始化
Future<bool> quicIsInitialized() =>
    RustLib.instance.api.crateFfiFfiQuicIsInitialized();

/// 清理 QUIC 连接池
Future<String> quicCleanup() => RustLib.instance.api.crateFfiFfiQuicCleanup();

/// 设置主网络链路 QUIC 传输开关
///
/// 启用后 LegadoClient 的 HTTPS 请求优先走 QUIC/HTTP3，失败自动 fallback 到 HTTP/2。
Future<String> netSetQuicEnabled({required bool enabled}) =>
    RustLib.instance.api.crateFfiFfiNetSetQuicEnabled(enabled: enabled);

/// 查询主网络链路 QUIC 传输开关状态
Future<bool> netIsQuicEnabled() =>
    RustLib.instance.api.crateFfiFfiNetIsQuicEnabled();

/// 构建书籍更新定时任务（返回 AutoTaskRule JSON）
Future<String> autoTaskBuildBookUpdate({
  required String bookUrl,
  required String bookName,
  required String bookAuthor,
  required String name,
}) => RustLib.instance.api.crateFfiFfiAutoTaskBuildBookUpdate(
  bookUrl: bookUrl,
  bookName: bookName,
  bookAuthor: bookAuthor,
  name: name,
);

/// 批量更新 cron 表达式（rules_json 为 AutoTaskRule 数组，ids_json 为 ID 数组，返回更新后的规则数组 JSON）
Future<String> autoTaskUpdateCronBatch({
  required String rulesJson,
  required String idsJson,
  required String cron,
}) => RustLib.instance.api.crateFfiFfiAutoTaskUpdateCronBatch(
  rulesJson: rulesJson,
  idsJson: idsJson,
  cron: cron,
);

/// 准备导入任务（合并本地运行时状态，返回合并后的任务数组 JSON）
Future<String> autoTaskPrepareImported({
  required String localTasksJson,
  required String importedJson,
}) => RustLib.instance.api.crateFfiFfiAutoTaskPrepareImported(
  localTasksJson: localTasksJson,
  importedJson: importedJson,
);

/// 执行任务协议（protocol_json 为 TaskProtocol，返回 TaskResult JSON）
Future<String> autoTaskExecute({required String protocolJson}) =>
    RustLib.instance.api.crateFfiFfiAutoTaskExecute(protocolJson: protocolJson);

/// 带 ID 执行任务协议（返回 TaskResult JSON）
Future<String> autoTaskExecuteWithId({
  required String protocolJson,
  required String taskId,
}) => RustLib.instance.api.crateFfiFfiAutoTaskExecuteWithId(
  protocolJson: protocolJson,
  taskId: taskId,
);

/// 规范化脚本（去除 @js: 前缀或 <js></js> 包裹）
Future<String> autoTaskNormalizeScript({required String script}) =>
    RustLib.instance.api.crateFfiFfiAutoTaskNormalizeScript(script: script);

/// 判断书籍是否允许刷新目录
Future<bool> autoTaskCanRefreshToc({
  required bool canUpdate,
  required bool respectCanUpdate,
}) => RustLib.instance.api.crateFfiFfiAutoTaskCanRefreshToc(
  canUpdate: canUpdate,
  respectCanUpdate: respectCanUpdate,
);

/// 查找书籍更新任务（tasks_json 为 AutoTaskRule 数组，返回匹配任务 JSON 或 null）
Future<String> autoTaskFindBookUpdate({
  required String tasksJson,
  required String bookUrl,
  required String bookName,
  required String bookAuthor,
}) => RustLib.instance.api.crateFfiFfiAutoTaskFindBookUpdate(
  tasksJson: tasksJson,
  bookUrl: bookUrl,
  bookName: bookName,
  bookAuthor: bookAuthor,
);

/// 解析 cron 表达式计算下次执行时间（Unix 毫秒，无法解析返回 -1）
Future<PlatformInt64> autoTaskNextDueAt({
  required String cron,
  required PlatformInt64 fromMs,
}) => RustLib.instance.api.crateFfiFfiAutoTaskNextDueAt(
  cron: cron,
  fromMs: fromMs,
);

/// 将播放模式写入 readConfig JSON（返回更新后的 JSON）
Future<String> audioWithPlayMode({String? readConfig, required int playMode}) =>
    RustLib.instance.api.crateFfiFfiAudioWithPlayMode(
      readConfig: readConfig,
      playMode: playMode,
    );

/// 解析听书书籍（返回 Book JSON 或 null）
///
/// 请求 URL 为空时返回缓存书籍；缓存匹配时直接返回；否则按 URL 查库。
Future<String> audioResolvePlayBook({
  String? requestedBookUrl,
  String? cachedBookJson,
}) => RustLib.instance.api.crateFfiFfiAudioResolvePlayBook(
  requestedBookUrl: requestedBookUrl,
  cachedBookJson: cachedBookJson,
);
