// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 书籍格式检测结果
class DetectFormatResult {
  /// 检测到的格式
  final String format;

  /// 文件路径
  final String path;

  const DetectFormatResult({required this.format, required this.path});

  @override
  int get hashCode => format.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DetectFormatResult &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          path == other.path;
}

/// 导入结果
class ImportResult {
  /// 是否成功
  final bool success;

  /// 导入的书籍信息（成功时）
  final Book? book;

  /// 错误信息（失败时）
  final String? error;

  const ImportResult({required this.success, this.book, this.error});

  @override
  int get hashCode => success.hashCode ^ book.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          book == other.book &&
          error == other.error;
}
