// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 章节列表响应（包含章节概要信息）
class ChapterListResponse {
  /// 章节总数
  final int total;

  /// 章节列表
  final List<BookChapter> chapters;

  const ChapterListResponse({required this.total, required this.chapters});

  @override
  int get hashCode => total.hashCode ^ chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterListResponse &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          chapters == other.chapters;
}
