// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// RSS 文章项
class RssArticle {
  /// 标题
  final String title;

  /// 链接
  final String link;

  /// 描述
  final String? description;

  /// 发布日期
  final String? pubDate;

  /// 图片 URL
  final String? imageUrl;

  const RssArticle({
    required this.title,
    required this.link,
    this.description,
    this.pubDate,
    this.imageUrl,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      link.hashCode ^
      description.hashCode ^
      pubDate.hashCode ^
      imageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RssArticle &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          link == other.link &&
          description == other.description &&
          pubDate == other.pubDate &&
          imageUrl == other.imageUrl;
}
