// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 搜索结果项
class SearchResult {
  /// 书源 URL
  final String sourceUrl;

  /// 书源名称
  final String sourceName;

  /// 书籍名称
  final String bookName;

  /// 作者
  final String author;

  /// 详情页 URL
  final String bookUrl;

  /// 最新章节
  final String? latestChapter;

  /// 简介
  final String? intro;

  /// 封面 URL
  final String? coverUrl;

  const SearchResult({
    required this.sourceUrl,
    required this.sourceName,
    required this.bookName,
    required this.author,
    required this.bookUrl,
    this.latestChapter,
    this.intro,
    this.coverUrl,
  });

  @override
  int get hashCode =>
      sourceUrl.hashCode ^
      sourceName.hashCode ^
      bookName.hashCode ^
      author.hashCode ^
      bookUrl.hashCode ^
      latestChapter.hashCode ^
      intro.hashCode ^
      coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          sourceUrl == other.sourceUrl &&
          sourceName == other.sourceName &&
          bookName == other.bookName &&
          author == other.author &&
          bookUrl == other.bookUrl &&
          latestChapter == other.latestChapter &&
          intro == other.intro &&
          coverUrl == other.coverUrl;
}
