// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rss_source.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$RssSourceImpl _$$RssSourceImplFromJson(Map<String, dynamic> json) =>
    _$RssSourceImpl(
      sourceUrl: json['sourceUrl'] as String? ?? '',
      sourceName: json['sourceName'] as String? ?? '',
      sourceIcon: json['sourceIcon'] as String? ?? '',
      sourceGroup: json['sourceGroup'] as String?,
      sourceComment: json['sourceComment'] as String?,
      enabled: json['enabled'] as bool? ?? true,
      variableComment: json['variableComment'] as String?,
      jsLib: json['jsLib'] as String?,
      enabledCookieJar: json['enabledCookieJar'] as bool?,
      concurrentRate: json['concurrentRate'] as String?,
      header: json['header'] as String?,
      loginUrl: json['loginUrl'] as String?,
      loginUi: json['loginUi'] as String?,
      loginCheckJs: json['loginCheckJs'] as String?,
      coverDecodeJs: json['coverDecodeJs'] as String?,
      sortUrl: json['sortUrl'] as String?,
      singleUrl: json['singleUrl'] as bool? ?? false,
      articleStyle: (json['articleStyle'] as num?)?.toInt() ?? 0,
      ruleArticles: json['ruleArticles'] as String?,
      ruleNextPage: json['ruleNextPage'] as String?,
      ruleTitle: json['ruleTitle'] as String?,
      rulePubDate: json['rulePubDate'] as String?,
      ruleDescription: json['ruleDescription'] as String?,
      ruleImage: json['ruleImage'] as String?,
      ruleLink: json['ruleLink'] as String?,
      ruleContent: json['ruleContent'] as String?,
      contentWhitelist: json['contentWhitelist'] as String?,
      contentBlacklist: json['contentBlacklist'] as String?,
      shouldOverrideUrlLoading: json['shouldOverrideUrlLoading'] as String?,
      style: json['style'] as String?,
      enableJs: json['enableJs'] as bool? ?? true,
      loadWithBaseUrl: json['loadWithBaseUrl'] as bool? ?? true,
      injectJs: json['injectJs'] as String?,
      preloadJs: json['preloadJs'] as String?,
      startHtml: json['startHtml'] as String?,
      startStyle: json['startStyle'] as String?,
      startJs: json['startJs'] as String?,
      showWebLog: json['showWebLog'] as bool? ?? false,
      lastUpdateTime: (json['lastUpdateTime'] as num?)?.toInt() ?? 0,
      customOrder: (json['customOrder'] as num?)?.toInt() ?? 0,
      rssType: (json['type'] as num?)?.toInt() ?? 0,
      preload: json['preload'] as bool? ?? false,
      cacheFirst: json['cacheFirst'] as bool? ?? false,
      searchUrl: json['searchUrl'] as String?,
    );

Map<String, dynamic> _$$RssSourceImplToJson(_$RssSourceImpl instance) =>
    <String, dynamic>{
      'sourceUrl': instance.sourceUrl,
      'sourceName': instance.sourceName,
      'sourceIcon': instance.sourceIcon,
      'sourceGroup': instance.sourceGroup,
      'sourceComment': instance.sourceComment,
      'enabled': instance.enabled,
      'variableComment': instance.variableComment,
      'jsLib': instance.jsLib,
      'enabledCookieJar': instance.enabledCookieJar,
      'concurrentRate': instance.concurrentRate,
      'header': instance.header,
      'loginUrl': instance.loginUrl,
      'loginUi': instance.loginUi,
      'loginCheckJs': instance.loginCheckJs,
      'coverDecodeJs': instance.coverDecodeJs,
      'sortUrl': instance.sortUrl,
      'singleUrl': instance.singleUrl,
      'articleStyle': instance.articleStyle,
      'ruleArticles': instance.ruleArticles,
      'ruleNextPage': instance.ruleNextPage,
      'ruleTitle': instance.ruleTitle,
      'rulePubDate': instance.rulePubDate,
      'ruleDescription': instance.ruleDescription,
      'ruleImage': instance.ruleImage,
      'ruleLink': instance.ruleLink,
      'ruleContent': instance.ruleContent,
      'contentWhitelist': instance.contentWhitelist,
      'contentBlacklist': instance.contentBlacklist,
      'shouldOverrideUrlLoading': instance.shouldOverrideUrlLoading,
      'style': instance.style,
      'enableJs': instance.enableJs,
      'loadWithBaseUrl': instance.loadWithBaseUrl,
      'injectJs': instance.injectJs,
      'preloadJs': instance.preloadJs,
      'startHtml': instance.startHtml,
      'startStyle': instance.startStyle,
      'startJs': instance.startJs,
      'showWebLog': instance.showWebLog,
      'lastUpdateTime': instance.lastUpdateTime,
      'customOrder': instance.customOrder,
      'type': instance.rssType,
      'preload': instance.preload,
      'cacheFirst': instance.cacheFirst,
      'searchUrl': instance.searchUrl,
    };
