// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ⚠️ frb 构件配对纪律警示（Task #55 F2）：frb codegen 变更后（如新增/删除
// 绑定导致 funcId 分派表整体重编号），.so / .dll 原生库与 Dart 生成物
// （ffi.dart / frb_generated*.dart）必须【原子重建】：同一次 codegen 后
// 同时重新编译 Rust 侧并重新生成 Dart 侧，禁止将新 Dart 生成物与旧
// 预构建 .so 混配（反之亦然），否则 funcId 错位会调用到错误的 Rust
// 函数，造成数据损坏或崩溃。frb_generated.dart 被 gitignore 不入库，
// 本机两侧同步状态以构建机 codegen 结果为准。

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_json`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `from`, `from`

/// frb 桥接错误类型
///
/// 所有桥接函数统一返回 `Result<T, BridgeError>`。
/// frb 会自动将其映射为 Dart 异常。
class BridgeError implements FrbException {
  /// 错误描述信息
  final String message;

  const BridgeError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}
