wrote D:\OH-WorkSpace\LegadoTeam\legado\docs\parity_shots\queue_smoke_20260920\logincheck_probe_insert.sql
============================================================
-- loginCheckJs 实机探针：停用现有源 + 插入 4 探针（幂等）
DELETE FROM book_sources WHERE bookSourceUrl LIKE 'http://127.0.0.1:18080/probe%';
UPDATE book_sources SET enabled=0 WHERE bookSourceUrl NOT LIKE 'http://127.0.0.1:18080/probe%';
INSERT INTO book_sources (bookSourceUrl, bookSourceName, bookSourceGroup, bookSourceType, enabled, enabledExplore, searchUrl, ruleSearch, ruleBookInfo, loginCheckJs, lastUpdateTime, respondTime, weight) VALUES ('http://127.0.0.1:18080/probeA', 'S0P-A', 'S0PROBE', 0, 1, 1, 'http://127.0.0.1:18080/probeA/search?kw={{key}}', '{"bookList":".book-item","name":".name","author":".author","bookUrl":".name@href"}', '{"name":".title","author":".author"}', 'result.code() == 200', 1789849440903, 0, 0);
INSERT INTO book_sources (bookSourceUrl, bookSourceName, bookSourceGroup, bookSourceType, enabled, enabledExplore, searchUrl, ruleSearch, ruleBookInfo, loginCheckJs, lastUpdateTime, respondTime, weight) VALUES ('http://127.0.0.1:18080/probeC', 'S0P-C', 'S0PROBE', 0, 1, 1, 'http://127.0.0.1:18080/probeC/search?kw={{key}}', '{"bookList":".book-item","name":".name","author":".author","bookUrl":".name@href"}', '{"name":".title","author":".author"}', 'result.code() == 200 ? { code: 200, body: ''<html><body><div class="book-item"><a class="name" href="/alt/book/1">修改后书名</a><span class="author">修改后作者</span></div></body></html>'', url: ''http://127.0.0.1:18080/probeC/alt'' } : false', 1789849440903, 0, 0);
INSERT INTO book_sources (bookSourceUrl, bookSourceName, bookSourceGroup, bookSourceType, enabled, enabledExplore, searchUrl, ruleSearch, ruleBookInfo, loginCheckJs, lastUpdateTime, respondTime, weight) VALUES ('http://127.0.0.1:18080/probeD', 'S0P-D', 'S0PROBE', 0, 1, 1, 'http://127.0.0.1:18080/probeD/search?kw={{key}}', '{"bookList":".book-item","name":".name","author":".author","bookUrl":".name@href"}', '{"name":".title","author":".author"}', 'result.code() == 500 ? { code: 200, body: ''<html><body><div class="book-item"><a class="name" href="/rec/book/1">恢复后书名</a><span class="author">恢复后作者</span></div></body></html>'', url: ''http://127.0.0.1:18080/probeD/rec'' } : false', 1789849440903, 0, 0);
INSERT INTO book_sources (bookSourceUrl, bookSourceName, bookSourceGroup, bookSourceType, enabled, enabledExplore, searchUrl, ruleSearch, ruleBookInfo, loginCheckJs, lastUpdateTime, respondTime, weight) VALUES ('http://127.0.0.1:18080/probeE', 'S0P-E', 'S0PROBE', 0, 1, 1, 'http://127.0.0.1:18080/probeE/search?kw={{key}}', '{"bookList":".book-item","name":".name","author":".author","bookUrl":".name@href"}', '{"name":".title","author":".author"}', 'result.code() == 500 ? { code: 500, body: result.body(), url: result.url() } : false', 1789849440903, 0, 0);

